// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/auth/logout.post').default>>>>
    }
    '/api/auth/refresh': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/auth/refresh.post').default>>>>
    }
    '/api/product/detail': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/product/detail').default>>>>
    }
    '/api/product/list': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/product/list').default>>>>
    }
    '/api/system/menus/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/system/menus/create.post').default>>>>
    }
    '/api/system/menus/delete': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/system/menus/delete.post').default>>>>
    }
    '/api/system/menus/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/system/menus/list.get').default>>>>
    }
    '/api/system/menus/update': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/system/menus/update.put').default>>>>
    }
    '/api/system/roles/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/system/roles/create.post').default>>>>
    }
    '/api/system/roles/delete': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/system/roles/delete.post').default>>>>
    }
    '/api/system/roles/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/system/roles/list.get').default>>>>
    }
    '/api/system/roles/update': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/system/roles/update.put').default>>>>
    }
    '/api/system/users/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/system/users/create.post').default>>>>
    }
    '/api/system/users/delete': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/system/users/delete.post').default>>>>
    }
    '/api/system/users/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/system/users/list.get').default>>>>
    }
    '/api/system/users/update': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/system/users/update.put').default>>>>
    }
    '/api/table/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/table/list.get').default>>>>
    }
    '/api/user/info': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/user/info').default>>>>
    }
    '/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/[...]').default>>>>
    }
    '/ws/chat': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/ws/chat').default>>>>
    }
  }
}
export {}